### PR TITLE
Rearranged typeof check to handle null parameter

### LINKED ISSUE #2493: Invoking custom helper I.methodName(null) method resulted into crash due to a logic error in lib/step.js
#### What are you trying to achieve?

I am trying to invoke a custom helper `I.methodName(null)` method with null argument to assert **null** value present in one of the json field.

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
     Cannot read property 'toString' of null
  ypeError: Cannot read property 'toString' of null
      at G:\CodeceptJS-Test\node_modules\codeceptjs\lib\step.js:115:22
      at Array.map (<anonymous>)
      at Step.humanizeArgs (node_modules\codeceptjs\lib\step.js:98:22)
      at Step.toString (node_modules\codeceptjs\lib\step.js:133:67)
      at Object.emit (node_modules\codeceptjs\lib\event.js:112:24)
```

> Provide test source code if related

My Helper class looks like below:

```js
// eslint-disable-next-line no-undef
const Helper     = codecept_helper;
const { expect } = require( 'chai' );

class ChaiExtraHelper extends Helper{

  assertNull( data ){

    return expect( data ).to.be.null;
  
  }

}

module.exports = ChaiExtraHelper;

```

My test looks like below:
```
I.assertNull(null);
```

### Details

* CodeceptJS version: 2.6.6
* NodeJS Version: 12.13.0
* Operating System: Windows 10
* puppeteer || webdriverio || protractor || testcafe version (if related)

### PR DESCRIPTION
**Pull request by sjana-aj**
Error:
Cannot read property 'toString' of null
  typeError: Cannot read property 'toString' of null
      at G:\CodeceptJS-Test\node_modules\codeceptjs\lib\step.js:115:22

Solution: Rearranged typeof check to handle crash when helper method is called with null parameter.

## Motivation/Description of the PR
- Resolves #2493 .

Applicable helpers:

- [x] WebDriver
- [x] Puppeteer
- [x] Nightmare
- [x] REST
- [x] FileHelper
- [x] Appium
- [x] Protractor
- [x] TestCafe
- [x] Playwright

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [x] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

File: lib/step.js [hunk 1]
```diff
@@ -112,10 +112,10 @@ class Step {
         return `${arg}`;
       } else if (arg instanceof Secret) {
         return '*****';
-      } else if (arg.toString && arg.toString() !== '[object Object]') {
-        return arg.toString();
       } else if (typeof arg === 'object') {
         return JSON.stringify(arg);
+      } else if (arg.toString && arg.toString() !== '[object Object]') {
```
Comment (Vorobeyko) [inline lib/step.js:117]: You can checks that arg is not null (undefined) at the beginning. 
`arg && arg.toString && arg.toString() !== '[object Object]'`
And not rearrange conditions.

File: lib/step.js [hunk 2]
```diff
@@ -112,10 +112,10 @@ class Step {
         return `${arg}`;
       } else if (arg instanceof Secret) {
         return '*****';
-      } else if (arg.toString && arg.toString() !== '[object Object]') {
-        return arg.toString();
       } else if (typeof arg === 'object') {
```
Comment (Vorobeyko) [inline lib/step.js:115]: And if arg is null, this line will return true, because null it is object ) 
And `humanizeArgs` return sting like `"null"`. 

Maybe we checks of null as first condition?

Comment (sjana-aj) [reply lib/step.js:115]: @Vorobeyko `else if (typeof arg === 'object')` handles when arg is sent as null and `humanizeArgs` return sting `"null"` but the real issue here is that `else if (arg.toString && arg.toString() !== '[object Object]')` check comes before `else if (typeof arg === 'object')` check and breaks the condition as `arg.toString()` fails to work on `arg=null` value, so I thought of not adding any extra check and rearrange our checks a bit which will not hopefully create any side effect and handles the null condition well without having to apply any additional check. Would love to hear your feedback on this pls.

File: lib/step.js (hunk 1 above)
Comment (sjana-aj) [reply lib/step.js:117]: @Vorobeyko pls see my comment below

File: lib/step.js (hunk 2 above)
Comment (sjana-aj) [reply lib/step.js:115]: @Vorobeyko just wanted to check if you found time to look through my comment pls

**Comment by DavertMik** [comment]
Sorry, @sjana-aj 
@Vorobeyko might be on vacation and I think I will need his approval to merge this PR
I hope we will do that soon

**Comment by sjana-aj** [comment]
np at all @DavertMik , thanks for letting me know 👍

File: lib/step.js (hunk 2 above)
Comment (Vorobeyko) [reply lib/step.js:115]: @sjana-aj Hi, sorry for late. 
I think you must to add additionally checks on top like:
```js
if (!args) {
  return ''
}
```

And this all. 
Args never been null or undefined on line `arg.toString && arg.toString() !== '[object Object]'`

**Comment by sjana-aj** [comment]
@Vorobeyko thanks for your comments. I just made the changes, can you pls check again?

File: lib/step.js [hunk 3]
```diff
@@ -95,6 +95,9 @@ class Step {
 
   /** @return {string} */
   humanizeArgs() {
+    if ( !args ) {
```
Comment (Vorobeyko) [inline lib/step.js:98]: this.args

Comment (sjana-aj) [reply lib/step.js]: I see, updated method now, pls check again

Comment (Vorobeyko) [reply lib/step.js]: hm... interested, why some CI jobs not started)

Comment (sjana-aj) [reply lib/step.js]: yup, I noticed that too. Is there some log available to investigate the cause?

**Comment by DavertMik** [comment]
Thank you!

**Comment by sjana-aj** [comment]
Thank you @DavertMik 👍
